#!/usr/bin/env python3
"""GUI for entering and saving broker credentials to .env file."""
import tkinter as tk
from tkinter import ttk, messagebox
from pathlib import Path

ENV_PATH = Path(__file__).resolve().parent / ".env"

BROKERS = [
    {
        "name": "BBAE",
        "fields": [
            ("BBAE_USER", "Email / Username"),
            ("BBAE_PASSWORD", "Password"),
        ],
    },
    {
        "name": "Chase",
        "fields": [
            ("CHASE_USERNAME", "Username"),
            ("CHASE_PASSWORD", "Password"),
        ],
    },
    {
        "name": "DSPAC",
        "fields": [
            ("DSPAC_USER", "Email / Username"),
            ("DSPAC_PASSWORD", "Password"),
        ],
    },
    {
        "name": "Fennel",
        "fields": [
            ("FENNEL_EMAIL", "Email(s) — comma-separated for multiple"),
        ],
    },
    {
        "name": "Fidelity",
        "fields": [
            ("FIDELITY_USERNAME", "Username"),
            ("FIDELITY_PASSWORD", "Password"),
            ("FIDELITY_TOTP_SECRET", "TOTP Secret (optional)"),
        ],
        "multi_hint": "For multiple logins use FIDELITY=user:pass:totp,user2:pass2:totp2",
        "multi_key": "FIDELITY",
    },
    {
        "name": "Public",
        "fields": [
            ("PUBLIC_SECRET_TOKEN_1", "Secret Token 1"),
            ("PUBLIC_SECRET_TOKEN_2", "Secret Token 2 (optional)"),
            ("PUBLIC_SECRET_TOKEN_3", "Secret Token 3 (optional)"),
        ],
    },
    {
        "name": "Robinhood",
        "fields": [
            ("ROBINHOOD_USERNAME", "Username"),
            ("ROBINHOOD_PASSWORD", "Password"),
        ],
        "multi_hint": "For multiple logins use ROBINHOOD=user:pass,user2:pass2",
        "multi_key": "ROBINHOOD",
    },
    {
        "name": "Schwab",
        "fields": [
            ("SCHWAB_USERNAME", "Username"),
            ("SCHWAB_PASSWORD", "Password"),
            ("SCHWAB_TOTP_SECRET", "TOTP Secret (optional)"),
        ],
        "multi_hint": "For multiple logins use SCHWAB=user:pass:totp,user2:pass2:totp2",
        "multi_key": "SCHWAB",
    },
    {
        "name": "SoFi",
        "fields": [
            ("SOFI_USERNAME", "Username"),
            ("SOFI_PASSWORD", "Password"),
            ("SOFI_TOTP_SECRET", "TOTP Secret (optional)"),
        ],
    },
    {
        "name": "Wells Fargo",
        "fields": [
            ("WELLSFARGO_USERNAME", "Username"),
            ("WELLSFARGO_PASSWORD", "Password"),
        ],
    },
]


def load_existing() -> dict:
    vals = {}
    if ENV_PATH.exists():
        for line in ENV_PATH.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            if "=" in line:
                k, v = line.split("=", 1)
                vals[k.strip()] = v.strip()
    return vals


def save_env(entries: dict) -> None:
    lines = [
        "# Broker credentials — generated by setup_gui.py",
        "",
    ]
    for broker in BROKERS:
        lines.append(f"# --- {broker['name']} ---")
        if "multi_key" in broker:
            mk = broker["multi_key"]
            if entries.get(mk):
                lines.append(f"{mk}={entries[mk]}")
            else:
                for key, _ in broker["fields"]:
                    val = entries.get(key, "")
                    if val:
                        lines.append(f"{key}={val}")
        else:
            for key, _ in broker["fields"]:
                val = entries.get(key, "")
                if val:
                    lines.append(f"{key}={val}")
        lines.append("")

    ENV_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")


class App(tk.Tk):
    def __init__(self):
        super().__init__()
        self.title("Broker Login Setup")
        self.configure(bg="#1e1e2e")
        self.resizable(True, True)
        self.minsize(580, 400)

        style = ttk.Style(self)
        style.theme_use("clam")
        style.configure("TNotebook", background="#1e1e2e", borderwidth=0)
        style.configure("TNotebook.Tab", background="#2a2a3e", foreground="#ccc",
                         padding=[12, 6], font=("Segoe UI", 9))
        style.map("TNotebook.Tab",
                   background=[("selected", "#3a3a5e")],
                   foreground=[("selected", "#fff")])
        style.configure("TFrame", background="#1e1e2e")
        style.configure("TLabel", background="#1e1e2e", foreground="#ccc", font=("Segoe UI", 10))
        style.configure("Hint.TLabel", background="#1e1e2e", foreground="#888", font=("Segoe UI", 8))
        style.configure("TEntry", fieldbackground="#2a2a3e", foreground="#eee",
                         insertcolor="#eee", font=("Consolas", 10))
        style.configure("Save.TButton", font=("Segoe UI", 11, "bold"), padding=[20, 8])

        existing = load_existing()
        self.entries: dict[str, tk.StringVar] = {}

        notebook = ttk.Notebook(self)
        notebook.pack(fill="both", expand=True, padx=10, pady=(10, 5))

        for broker in BROKERS:
            frame = ttk.Frame(notebook)
            notebook.add(frame, text=f"  {broker['name']}  ")

            row = 0
            if broker.get("multi_hint"):
                hint = ttk.Label(frame, text=broker["multi_hint"], style="Hint.TLabel")
                hint.grid(row=row, column=0, columnspan=2, sticky="w", padx=15, pady=(12, 2))
                row += 1

                mk = broker["multi_key"]
                var = tk.StringVar(value=existing.get(mk, ""))
                self.entries[mk] = var
                ttk.Label(frame, text=f"{mk} (multi):").grid(
                    row=row, column=0, sticky="e", padx=(15, 5), pady=4)
                ttk.Entry(frame, textvariable=var, width=50).grid(
                    row=row, column=1, sticky="ew", padx=(0, 15), pady=4)
                row += 1

                sep = ttk.Label(frame, text="— OR use single-account fields below —", style="Hint.TLabel")
                sep.grid(row=row, column=0, columnspan=2, padx=15, pady=(6, 2))
                row += 1

            for key, label in broker["fields"]:
                var = tk.StringVar(value=existing.get(key, ""))
                self.entries[key] = var
                ttk.Label(frame, text=f"{label}:").grid(
                    row=row, column=0, sticky="e", padx=(15, 5), pady=4)
                show = "*" if "password" in key.lower() else ""
                e = ttk.Entry(frame, textvariable=var, width=50, show=show)
                e.grid(row=row, column=1, sticky="ew", padx=(0, 15), pady=4)
                row += 1

            frame.columnconfigure(1, weight=1)

        btn_frame = ttk.Frame(self)
        btn_frame.pack(fill="x", padx=10, pady=10)
        save_btn = ttk.Button(btn_frame, text="Save .env", style="Save.TButton", command=self.on_save)
        save_btn.pack(side="right")

        self.status = ttk.Label(btn_frame, text="", style="Hint.TLabel")
        self.status.pack(side="left", padx=5)

    def on_save(self):
        data = {k: v.get().strip() for k, v in self.entries.items()}
        filled = sum(1 for v in data.values() if v)
        if filled == 0:
            messagebox.showwarning("Empty", "No credentials entered.")
            return
        save_env(data)
        self.status.config(text=f"Saved to {ENV_PATH}", foreground="#4caf50")
        messagebox.showinfo("Saved", f"Credentials saved to:\n{ENV_PATH}\n\n{filled} field(s) set.")


if __name__ == "__main__":
    App().mainloop()
